name: Build VyOS Image
on:
  push:
    branches: [vyos-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone vyos-build repo
        run: git clone -b crux --single-branch https://github.com/vyos/vyos-build

      - name: Make ISO
        working-directory: ./vyos-build
        run: |
          docker run --rm -t --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:crux bash -c \
          "./configure --architecture amd64 --build-by 'petoem@github-runner' --build-type release --version 1.2 ; sudo make iso"

      - name: Show build result
        run: ls -lah ./vyos-build/build

      - name: Upload ISO to artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: vyos-image-1.2
          path: ./vyos-build/build/vyos-1.2-amd64.iso
